graph TD
    Client[Client<br/>Browser / Mobile App]
    
    subgraph FastAPI_App [FastAPI Application]
        direction TB
        CORS[CORS Middleware]
        JWT[JWT Auth Middleware]
        
        subgraph Routers [API Routers]
            R_Auth[/auth]
            R_Books[/books]
            R_Loans[/loans]
            R_Stats[/stats]
            R_Users[/users]
        end
        
        subgraph Logic [Business Logic Layer]
            Val[Validation Pydantic]
            RBAC[Authorization RBAC]
            Trans[Transaction Handing]
        end
        
        subgraph DB_Layer [Database Layer Motor]
            Driver[Async MongoDB Driver]
            Pool[Connection Pooling]
        end
    end
    
    Mongos[MongoDB Cluster<br/>mongos1:27020]

    Client -- "HTTPS/REST JSON" --> CORS
    CORS --> JWT
    JWT --> Routers
    
    Routers --> Logic
    Logic --> DB_Layer
    DB_Layer -- "MongoDB Wire Protocol" --> Mongos